### ISSUE TITLE
protccrxn2.py doesn't add the correct number of protons

### ISSUE THREAD

**Issue by Ianiusha** [jensengroup/RegioSQM#1]
I tried to reproduce the results in the RegioSQM paper, but there is a problem in this script. It does not add the correct number of protons. For example, for compound 83 of the published test set ( c1(ccc(=O)[nH]c1C(=O)OC)C ) you end up with one aromatic carbon that has 2 protons, and the other one that has 3, like so:
comp83 COC(=O)C1=C(C)C=CC(=O)N1
comp83+_1 COC(=O)C1=C(C)C[CH3+]C(=O)N1 1
comp83+_2 COC(=O)C1=C(C)[CH3+]CC(=O)N1 2

**Comment by jhjensen2** [comment]
I can't reproduce this using my version of the code.

What version of RDKit are you using?  I am using 2016.09.2
You can find out by 

from rdkit import rdBase
print(rdBase.rdkitVersion)

**Comment by Ianiusha** [comment]
yep, changed rdKit version, now it works :) thanks for the reply!
