### ISSUE TITLE
Clearer discern «green» and «red»

### ISSUE THREAD

**Issue by nbehrnd** [jensengroup/RegioSQM#2]
Beside the questions already answered in section «FAQ», it were a helpful reminder to add
- that the cut-off threshold for the green marks is a ΔG of 1 kcal/mol, and for the red marks of 3 kcal/mol
- thus, in case of red and green marks simultaneously present, the red marks indicate sites more favourable to an electrophilic substitution, than the ones marked by green.

**Comment by jhjensen2** [comment]
That's all explained in the paper, which one should read before using the method. Furthermore, the **green** atoms indicate sites more favourable to an electrophilic substitution, than the ones marked by red.
