### ISSUE TITLE
feature suggest, numerical label of the aromatic sites

### ISSUE THREAD

**Issue by nbehrnd** [jensengroup/RegioSQM#3]
At present, starting material and a possible product of reaction are compared with each other.  Probing each aromatic site, either
- the product's energy is at least 1 kcal/mol below the one of the starting material, and then is marked by a green circle, .or.
- the product's energy is at least 3 kcal/mol below the one of the starting material, and then marked by a red circle.

Using RegioSQM so far _via_ your web site only, I would like to suggest an additional mode; namely, that the differences
are seen right next to the carbon atom in question in an accuracy of one decimal.  This could provide a more gradual ranking of the sites in terms of electrophilic substitution, than the current three level binning of «not really»  (|ΔG| < 1 kcal/mol, no mark), «so la la» (1 < |ΔG| < 3 kcal / mol, green), or «good» (|ΔG| > 3 kcal / mol, red).  It could be presented like the following illustration:

![fictious_half](https://user-images.githubusercontent.com/19709084/86364842-3e88e100-bc68-11ea-87e6-0af0edb61c40.png)

Context:

A question about electrophilic substitution on [ChemistrySE](https://chemistry.stackexchange.com/questions/135795/which-is-the-major-product-of-bromination-of-3-dimethylaminobenzamide-ortho-o/135800#comment265561_135800) was answered with emphasis on steric hinderance.  A complementary perspective is to assume the starting material as derived from two mono-substituted benzenes, and recalling how these patterns would _preferentially_ direct the entrance of the new substitutent:

![test_half](https://user-images.githubusercontent.com/19709084/86365487-1baafc80-bc69-11ea-9496-2358273eb194.png)

With RegioSQM, the situation may be decomposed as in the following illustration:

![decomposition_040](https://user-images.githubusercontent.com/19709084/86366028-d4713b80-bc69-11ea-8b2b-d2add2b9c587.png)

RegioSQM indicates the position _para_ to the amide group as the one energetically most favourable for an electrophilic substitution; this aligns with the answer given on ChemSE.  On the other hand, the scrutiny of benzamide alone (bottom right) does not convey the preferred _meta_-diection by the amide group for a second substitution.

Thus, a number of monosubstituted benzenes were tested with subsitutents said to direct _preferentially_ to either _ortho_/_para_, or to _meta_ position.  For example, along the line of F -> Cl -> Br -> I, the preference for the former pattern becomes less visible (2020-07-21_question.pdf).  In the case of simultaneous presence of homo- and hetarenes (with_heterocylics.png), it equally could be highly instructive to have the version where atoms are joined by the note about ΔG as a numbers, too.

Thus I wish retaining the current three-level scale (none, green, red) as a scale generally applied, offering a quick survey across many possible molecules, as _one_ option.  Depending on core structure and substitutents already present, the changes expressed by ΔG however may vary from molecule to molecule in addition to the variation probing the sites within a molecule.  Thus, accessing the ΔG as numbers intends as path _complementary_ to the one already offered; preferentially both from the scripts deposit here, as well from the website dedicated as on-line service.

[2020-07-21_question.pdf](https://github.com/jensengroup/RegioSQM/files/4864739/2020-07-21_question.pdf)
[with_heterocylics.png](https://user-images.githubusercontent.com/19709084/86368823-28c9ea80-bc6d-11ea-952f-a64c06337520.png)

**Comment by jhjensen2** [comment]
> At present, starting material and a possible product of reaction are compared with each other. Probing each aromatic site, either

>the product's energy is at least 1 kcal/mol below the one of the starting material, and then is marked by a green circle, .or.
>the product's energy is at least 3 kcal/mol below the one of the starting material, and then marked by a red circle.

This is wrong. Please read the paper carefully.
